language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
install:
  - curl -sS https://getcomposer.org/installer | php
  - npm install
before_script:
  - php --version
  - php composer.phar composer --version
  - php composer.phar install
  - npm install -g grunt-cli
script: npm test
